### PR TITLE
Update gitignore pattern

### PR DESCRIPTION
**Pull request by hectorsector**
The instructions state that only the top-level `artifacts/` directory should match. I believe that means that the pattern needs to be `/artifacts/`, otherwise something like `hello/artifacts/a.md` would not be ignored. Could you confirm @mattdavis0351?

### CODE REVIEW

**Comment by mattdavis0351** [comment]
@hectorsector I think `artifacts/` is correct.  Here is a current tree from where I ran a test on this.

```
├── .gitignore
├── main.js
└── oranges
    ├── another.js
    └── bread
        └── more.js
```

If I add `bread/` to the `.gitignore` then the `bread` directory get's ignored.  

If I add `/bread/`, then `bread` does **not** get ignored

The catch 22 is that if I add `/oranges/` **or** `oranges/` to the `.gitignore` the results are identical.  The entire `oranges` dir and it's children are ignored.

**Comment by hectorsector** [comment]
Hm... interesting, so this is what I tested. We want to ignore only **parent artifacts/**, so on `git status` we should still see all the `artifacts` in subdirectories.

With `artifacts/`, we do not see any of the subdirectories:
```
➜ cat .gitignore
artifacts/

➜ tree .
.
├── README.md
├── a
│   ├── a.md
│   └── artifacts
│       └── b.md
├── artifacts
│   └── c.md
├── hello
│   └── artifacts
│       └── e.md
└── zsh.md

➜ git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.github/
	README.md
	a/
	zsh.md
```

With `/artifacts/`, we see the subdirectories:
```
➜ cat .gitignore
/artifacts/

➜ tree .
.
├── README.md
├── a
│   ├── a.md
│   └── artifacts
│       └── b.md
├── artifacts
│   └── c.md
├── hello
│   └── artifacts
│       └── e.md
└── zsh.md

➜ git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.github/
	README.md
	a/
	hello/
	zsh.md
```

**Comment by mattdavis0351** [comment]
@hectorsector I see what you are saying.  I'll push that change right now.

**Review by mattdavis0351 — APPROVED** [review]
should be good to 🚢

**Pull request merged**
